version: 1
formatters:
  default:
    format: '%(asctime)s %(levelname)s %(filename)s::%(funcName)s():%(lineno)s => %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: bot.log
    level: DEBUG
loggers:
  '':
    handlers: [console, file]
    level: DEBUG